default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geekhub_shop_development

test:
  <<: *default
  database: geekhub_shop_test

production:
  <<: *default
  database: geekhub_shop_production
  username: <%= Rails.application.credentials.db_user %>
  password: <%= Rails.application.credentials.db_password %>
